AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simplified YouTube MP3 Converter for Testing

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage

Resources:
  # API Gateway
  SimpleAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Simple Test Function
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: ./
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 30
      Events:
        TestAPI:
          Type: Api
          Properties:
            RestApiId: !Ref SimpleAPI
            Path: /api/test
            Method: get

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${SimpleAPI}.execute-api.${AWS::Region}.amazonaws.com/${Stage} 